<?php

namespace ChristmasShopBundle\Repository;

/**
 * SubcategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
